# -*- coding: utf-8 -*-
# Copyright (c) 2026, Cyvetech and contributors
# For license information, please see license.txt

import json
import frappe
from frappe import _
from frappe.utils import flt, fmt_money, format_datetime, get_datetime, formatdate


# ============================================================
# EXECUTE - Required by ERPNext for Script Reports
# This just proxies the standard General Ledger report
# ============================================================

def execute(filters=None):
    filters = filters or {}

    # Get data from standard General Ledger report
    from erpnext.accounts.report.general_ledger.general_ledger import execute as gl_execute
    return gl_execute(filters)


# ============================================================
# PDF EXPORT - called from Print PDF button
# ============================================================

@frappe.whitelist()
def get_pdf_html(filters, data):
    if isinstance(filters, str):
        filters = json.loads(filters)
    if isinstance(data, str):
        data = json.loads(data)

    company     = filters.get("company")
    company_doc = frappe.get_doc("Company", company) if company else None
    currency    = company_doc.default_currency if company_doc else "UGX"

    letter_head_html = build_company_header(company_doc)
    table_html       = build_pdf_table(data, currency)

    now = format_datetime(get_datetime(), "dd MMM yyyy HH:mm")
    css = get_pdf_css()

    from_date  = formatdate(filters.get("from_date")) if filters.get("from_date") else "All"
    to_date    = formatdate(filters.get("to_date"))   if filters.get("to_date")   else "All"

    filter_pairs = [
        ("Company",     str(company    or "")),
        ("From Date",   from_date),
        ("To Date",     to_date),
        ("Account",     filters.get("account")      or "All"),
        ("Party Type",  filters.get("party_type")   or "All"),
        ("Party",       filters.get("party")        or "All"),
        ("Cost Center", filters.get("cost_center")  or "All"),
        ("Project",     filters.get("project")      or "All"),
        ("Voucher No",  filters.get("voucher_no")   or "All"),
    ]
    filter_html = "".join(
        '<div class="filter-item">'
        '<span class="filter-label">' + lbl + ':</span> '
        '<span class="filter-value">' + str(val) + '</span>'
        '</div>'
        for lbl, val in filter_pairs
        if val and val not in ("All", "")
    )

    html = (
        "<!DOCTYPE html><html>"
        "<head><meta charset='UTF-8'>"
        "<title>General Ledger</title>"
        "<style>" + css + "</style>"
        "</head><body>"
        + letter_head_html
        + "<div class='report-header'>"
            "<div class='report-title'>"
                "<h1>General Ledger</h1>"
                "<div class='subtitle'>"
                "Period: " + from_date + " to " + to_date
                + " &nbsp;|&nbsp; Company: " + str(company or "")
                + "</div>"
            "</div>"
            "<div class='report-meta'>"
                "<div><span class='label'>Generated By:</span> "
                "<strong>" + str(frappe.session.user) + "</strong></div>"
                "<div><span class='label'>Date:</span> " + str(now) + "</div>"
            "</div>"
        "</div>"
        "<div class='filters-section'>"
            "<div class='filters-title'>Applied Filters</div>"
            "<div class='filters-grid'>" + filter_html + "</div>"
        "</div>"
        + table_html
        + "<div class='footer'>"
            "<div>General Ledger - " + str(company or "") + "</div>"
            "<div>Generated by " + str(frappe.session.user)
            + " on " + str(now) + "</div>"
        "</div>"
        "</body></html>"
    )

    return html


# ============================================================
# COMPANY HEADER
# ============================================================

def build_company_header(company_doc):
    if not company_doc:
        return ""

    letter_head_content = ""
    if company_doc.default_letter_head:
        try:
            lh  = frappe.get_doc("Letter Head", company_doc.default_letter_head)
            raw = lh.content or ""
            if raw:
                letter_head_content = frappe.render_template(
                    raw,
                    {"doc": frappe._dict({"company": company_doc.name})}
                )
        except Exception as e:
            frappe.log_error(str(e), "Letter Head Render Error")

    if letter_head_content:
        return '<div class="letter-head">' + letter_head_content + '</div>'

    logo_html = ""
    if company_doc.company_logo:
        logo_html = (
            '<img src="' + company_doc.company_logo + '" '
            'style="height:65px; max-width:220px; object-fit:contain;" />'
        )

    def field(f):
        return str(company_doc.get(f) or "")

    contact_lines = ""
    if field("address_line1"):
        contact_lines += "<div>" + field("address_line1") + "</div>"
    if field("address_line2"):
        contact_lines += "<div>" + field("address_line2") + "</div>"
    if field("city"):
        contact_lines += "<div>" + field("city") + "</div>"
    if field("phone_no"):
        contact_lines += "<div>Tel: "   + field("phone_no") + "</div>"
    if field("email"):
        contact_lines += "<div>Email: " + field("email")    + "</div>"
    if field("website"):
        contact_lines += "<div>Web: "   + field("website")  + "</div>"

    return (
        '<div class="letter-head">'
            '<div class="lh-inner">'
                '<div class="lh-logo">' + logo_html + '</div>'
                '<div class="lh-info">'
                    '<div class="lh-company-name">'
                    + company_doc.company_name + '</div>'
                    '<div class="lh-contact">' + contact_lines + '</div>'
                '</div>'
            '</div>'
        '</div>'
    )


# ============================================================
# TABLE BUILDER
# ============================================================

def build_pdf_table(data, currency):

    def fmt(v):
        return fmt_money(flt(v), currency=currency) if flt(v) else "-"

    def short(val, n=25):
        s = str(val or "")
        return s[:n] + ".." if len(s) > n else s

    headers = (
        '<tr>'
        '<th class="text-center" style="width:28px;">#</th>'
        '<th style="width:75px;">Date</th>'
        '<th style="width:155px;">Account</th>'
        '<th style="width:125px;">Voucher No</th>'
        '<th style="width:95px;">Voucher Type</th>'
        '<th style="width:75px;">Party Type</th>'
        '<th style="width:115px;">Party</th>'
        '<th style="width:115px;">Against</th>'
        '<th class="text-right" style="width:105px;">Debit</th>'
        '<th class="text-right" style="width:105px;">Credit</th>'
        '<th class="text-right" style="width:105px;">Balance</th>'
        '<th style="width:100px;">Cost Center</th>'
        '</tr>'
    )

    rows_html    = ""
    row_index    = 0
    total_debit  = 0
    total_credit = 0

    for row in data:
        if not isinstance(row, dict):
            continue

        account      = row.get("account") or ""
        posting_date = row.get("posting_date")
        debit        = flt(row.get("debit"))
        credit       = flt(row.get("credit"))
        balance      = row.get("balance")
        is_special   = not posting_date or not account

        if is_special:
            label = account or row.get("voucher_type") or "Opening"
            rows_html += (
                '<tr class="opening-row">'
                '<td colspan="8" class="text-right opening-label">'
                '<strong>' + short(label, 40) + '</strong></td>'
                '<td class="text-right"><strong>' + fmt(debit)   + '</strong></td>'
                '<td class="text-right"><strong>' + fmt(credit)  + '</strong></td>'
                '<td class="text-right"><strong>' + fmt(balance) + '</strong></td>'
                '<td></td>'
                '</tr>'
            )
        else:
            row_index    += 1
            total_debit  += debit
            total_credit += credit
            cls = "even" if row_index % 2 == 0 else "odd"

            rows_html += (
                '<tr class="' + cls + '">'
                '<td class="text-center row-num">' + str(row_index) + '</td>'
                '<td class="date-cell">'
                + (formatdate(posting_date) if posting_date else "-") + '</td>'
                '<td class="account-cell">' + short(account, 28)                  + '</td>'
                '<td class="voucher-cell">' + short(row.get("voucher_no"), 20)    + '</td>'
                '<td>'                      + short(row.get("voucher_type"), 18)  + '</td>'
                '<td>'                      + short(row.get("party_type"), 14)    + '</td>'
                '<td>'                      + short(row.get("party"), 18)         + '</td>'
                '<td>'                      + short(row.get("against"), 22)       + '</td>'
                '<td class="text-right debit-col">'
                + (fmt(debit)  if debit  else "-") + '</td>'
                '<td class="text-right credit-col">'
                + (fmt(credit) if credit else "-") + '</td>'
                '<td class="text-right balance-col">' + fmt(balance) + '</td>'
                '<td>' + short(row.get("cost_center"), 16) + '</td>'
                '</tr>'
            )

    # Grand Total
    rows_html += (
        '<tr class="totals-row">'
        '<td colspan="8" class="text-right"><strong>GRAND TOTAL</strong></td>'
        '<td class="text-right"><strong>' + fmt(total_debit)  + '</strong></td>'
        '<td class="text-right"><strong>' + fmt(total_credit) + '</strong></td>'
        '<td class="text-right"><strong>'
        + fmt(total_debit - total_credit) + '</strong></td>'
        '<td></td>'
        '</tr>'
    )

    return (
        '<table class="report-table">'
        '<thead>' + headers + '</thead>'
        '<tbody>' + rows_html + '</tbody>'
        '</table>'
    )


# ============================================================
# CSS
# ============================================================

def get_pdf_css():
    return (
        "@page { size: A4 landscape; margin: 7mm; }"
        "* { box-sizing:border-box; margin:0; padding:0; }"
        "body { font-family:'Helvetica Neue',Arial,sans-serif;"
        "       font-size:6.5pt; color:#2d3748; background:#fff; line-height:1.3; }"

        ".letter-head { margin-bottom:10px; padding-bottom:8px;"
        "               border-bottom:3px solid #4299e1; }"
        ".lh-inner { display:flex; justify-content:space-between;"
        "            align-items:center; padding:6px 0; }"
        ".lh-company-name { font-size:13pt; font-weight:700;"
        "                   color:#2d3748; margin-bottom:4px; }"
        ".lh-contact { font-size:7pt; color:#4a5568; line-height:1.7; }"

        ".report-header { display:flex; justify-content:space-between;"
        "    align-items:flex-start; margin-bottom:8px; padding:10px 14px;"
        "    color:white; border-radius:8px;"
        "    background:linear-gradient(135deg,#4299e1 0%,#667eea 50%,#764ba2 100%); }"
        ".report-title h1 { font-size:15pt; font-weight:700; margin-bottom:3px; }"
        ".report-title .subtitle { font-size:7.5pt; opacity:0.9; }"
        ".report-meta { text-align:right; font-size:7pt; }"
        ".report-meta .label { opacity:0.82; }"

        ".filters-section { background:#f0f4ff; border-left:4px solid #667eea;"
        "    padding:7px 12px; margin-bottom:8px; border-radius:4px; }"
        ".filters-title { font-size:7.5pt; font-weight:700; color:#5e72e4;"
        "    margin-bottom:3px; text-transform:uppercase; letter-spacing:0.5px; }"
        ".filters-grid { display:grid; grid-template-columns:repeat(5,1fr);"
        "    gap:3px 10px; }"
        ".filter-item { font-size:7pt; }"
        ".filter-label { font-weight:600; color:#4a5568; }"

        "table.report-table { width:100%; border-collapse:collapse;"
        "    font-size:6.2pt; margin-bottom:8px; }"
        "table.report-table thead {"
        "    background:linear-gradient(135deg,#4299e1 0%,#667eea 100%);"
        "    color:white; }"
        "table.report-table th { padding:5px 3px; font-weight:600; font-size:6pt;"
        "    text-transform:uppercase; letter-spacing:0.2px;"
        "    border:1px solid #5a92d4; }"
        "table.report-table td { padding:3px; border:1px solid #e2e8f0; }"
        "table.report-table tr.odd  { background:#ffffff; }"
        "table.report-table tr.even { background:#f7fafc; }"
        ".text-right  { text-align:right  !important; }"
        ".text-center { text-align:center !important; }"

        "tr.opening-row { background:#fffbeb !important; }"
        ".opening-label { color:#744210; font-size:7pt; }"

        "tr.totals-row {"
        "    background:linear-gradient(135deg,#4299e1,#667eea) !important;"
        "    color:white; font-weight:700; }"
        "tr.totals-row td { padding:6px 3px; border-color:#5a92d4; font-size:7pt; }"

        ".row-num      { color:#a0aec0; }"
        ".date-cell    { white-space:nowrap; }"
        ".account-cell { color:#2b6cb0; font-weight:500; }"
        ".voucher-cell { color:#2d3748; font-family:monospace; font-size:6pt; }"
        ".debit-col    { color:#c53030; font-weight:600; }"
        ".credit-col   { color:#276749; font-weight:600; }"
        ".balance-col  { color:#2d3748; font-weight:600; }"

        ".footer { margin-top:10px; padding-top:5px;"
        "    border-top:1px solid #e2e8f0; display:flex;"
        "    justify-content:space-between; font-size:6pt; color:#718096; }"

        "@media print {"
        "    body { -webkit-print-color-adjust:exact; print-color-adjust:exact; }"
        "    tr { page-break-inside:avoid; }"
        "    thead { display:table-header-group; }"
        "    tr.opening-row { page-break-after:avoid; }"
        "}"
    )