"""Branded printout for the standard Accounts Receivable reports.

Renders the same letterhead / gradient header / summary-card / table styling
as the other Cyvetech reports (helpers reused from Sales Analysis Report),
fed by the live report output including all Cyvetech enhancements (customer
name, A-Z sort, negative-balance filter, summarize by customer).
"""

import json

import frappe
from frappe import _
from frappe.utils import cint, escape_html, flt, fmt_money, format_datetime, formatdate, get_datetime

from cyvetech_reports.cyvetech_reports.report.sales_analysis_report.sales_analysis_report import (
	_company_header_html,
	get_pdf_css,
)

ALLOWED_REPORTS = ("Accounts Receivable", "Accounts Receivable Summary")
NUMERIC_TYPES = {"Currency", "Float", "Int"}


@frappe.whitelist()
def get_pdf_html(report_name, filters, visible_columns=None, summarize=0):
	if report_name not in ALLOWED_REPORTS:
		frappe.throw(_("Unsupported report: {0}").format(report_name))

	if isinstance(filters, str):
		filters = json.loads(filters or "{}")
	filters = filters or {}
	if isinstance(visible_columns, str):
		visible_columns = json.loads(visible_columns or "[]")
	visible_columns = visible_columns or []

	if cint(summarize):
		filters["summarize_by_customer"] = 1

	# make sure the report enhancements are active, then run the report the
	# same way the desk does (permission checks included)
	from cyvetech_reports.overrides.accounts_receivable import apply_patch

	apply_patch()

	import frappe.desk.query_report as query_report

	result = query_report.run(report_name, filters=filters, ignore_prepared_report=True)

	all_columns = [
		c for c in (result.get("columns") or []) if isinstance(c, dict) and c.get("fieldname")
	]
	rows = [r for r in (result.get("result") or []) if isinstance(r, dict) and r.get("party")]

	if visible_columns:
		columns = [c for c in all_columns if c["fieldname"] in visible_columns]
	else:
		columns = [c for c in all_columns if not c.get("hidden")]
	if not columns:
		frappe.throw(_("No fields selected to print"))

	company = filters.get("company") or frappe.db.get_single_value(
		"Global Defaults", "default_company"
	)
	company_doc = frappe.get_doc("Company", company) if company else None
	currency = (company_doc and company_doc.default_currency) or "USD"

	letter_head_html = _company_header_html(company_doc)
	filter_html = _build_filter_html(filters, company)
	cards_html = _build_summary_cards(rows, currency)
	headers_html, rows_html, totals_html = _build_table(columns, rows, currency)

	report_date = filters.get("report_date")
	subtitle = _("As at {0}").format(formatdate(report_date)) if report_date else ""
	if cint(filters.get("summarize_by_customer")):
		subtitle += (" &nbsp;|&nbsp; " if subtitle else "") + _("Summarized by Customer")

	now = format_datetime(get_datetime(), "dd MMM yyyy HH:mm")
	user = escape_html(str(frappe.session.user))
	title = escape_html(_(report_name))
	company_label = escape_html(str(company or ""))

	return (
		'<!DOCTYPE html><html><head><meta charset="UTF-8">'
		"<title>" + title + "</title>"
		"<style>" + get_pdf_css() + "</style></head><body>"
		+ letter_head_html
		+ '<div class="report-header">'
		'<div class="report-title">'
		"<h1>" + title + "</h1>"
		'<div class="subtitle">' + subtitle + "</div>"
		"</div>"
		'<div class="report-meta">'
		'<div><span class="label">' + _("Company") + ":</span> <strong>" + company_label + "</strong></div>"
		'<div><span class="label">' + _("Generated") + ":</span> " + str(now) + "</div>"
		'<div><span class="label">' + _("By") + ":</span> " + user + "</div>"
		"</div>"
		"</div>"
		'<div class="filters-section">'
		'<div class="filters-title">' + _("Applied Filters") + "</div>"
		'<div class="filters-grid">' + filter_html + "</div>"
		"</div>"
		+ cards_html
		+ '<table class="report-table"><thead>' + headers_html + "</thead>"
		"<tbody>" + rows_html + totals_html + "</tbody></table>"
		'<div class="signature-section">'
		'<div class="signature-box"><div class="signature-line"></div><div><strong>' + _("Prepared By") + "</strong></div></div>"
		'<div class="signature-box"><div class="signature-line"></div><div><strong>' + _("Verified By") + "</strong></div></div>"
		'<div class="signature-box"><div class="signature-line"></div><div><strong>' + _("Approved By") + "</strong></div></div>"
		"</div>"
		'<div class="footer">'
		"<div>" + title + " - " + company_label + "</div>"
		"<div>" + _("Generated by {0} on {1}").format(user, now) + "</div>"
		"</div>"
		"</body></html>"
	)


def _as_text(value):
	if isinstance(value, (list, tuple)):
		return ", ".join(str(v) for v in value if v)
	return str(value or "")


def _build_filter_html(filters, company):
	filter_map = [
		(_("Company"), _as_text(company)),
		(
			_("Report Date"),
			formatdate(filters.get("report_date")) if filters.get("report_date") else "",
		),
		(_("Ageing Based On"), _as_text(filters.get("ageing_based_on"))),
		(_("Ageing Range"), _as_text(filters.get("range"))),
		(_("Customer"), _as_text(filters.get("party"))),
		(_("Customer Group"), _as_text(filters.get("customer_group"))),
		(_("Territory"), _as_text(filters.get("territory"))),
		(_("Sales Person"), _as_text(filters.get("sales_person"))),
		(_("Sales Partner"), _as_text(filters.get("sales_partner"))),
		(_("Payment Terms Template"), _as_text(filters.get("payment_terms_template"))),
		(_("Negative Balances Removed"), _("Yes") if cint(filters.get("remove_negative_balance")) else ""),
		(_("Summarized by Customer"), _("Yes") if cint(filters.get("summarize_by_customer")) else ""),
	]

	html = ""
	for label, value in filter_map:
		if value:
			html += (
				'<div class="filter-item">'
				'<span class="filter-label">' + escape_html(str(label)) + ":</span> "
				'<span class="filter-value">' + escape_html(str(value)) + "</span>"
				"</div>"
			)
	return html


def _build_summary_cards(rows, currency):
	def col_sum(field):
		return sum(flt(r.get(field)) for r in rows)

	cards = [
		("card-blue", _("Invoiced"), fmt_money(col_sum("invoiced"), currency=currency)),
		("card-green", _("Paid"), fmt_money(col_sum("paid"), currency=currency)),
		("card-purple", _("Credit Note"), fmt_money(col_sum("credit_note"), currency=currency)),
		("card-red", _("Outstanding"), fmt_money(col_sum("outstanding"), currency=currency)),
		("card-grey", _("Customers"), str(len({r.get("party") for r in rows}))),
	]

	html = '<div class="summary-cards">'
	for css_class, label, value in cards:
		html += (
			'<div class="summary-card ' + css_class + '">'
			'<div class="label">' + escape_html(str(label)) + "</div>"
			'<div class="value">' + value + "</div>"
			"</div>"
		)
	return html + "</div>"


def _build_table(columns, rows, currency):
	def is_numeric(col):
		return col.get("fieldtype") in NUMERIC_TYPES

	header_cells = ""
	for col in columns:
		css = ' class="text-right"' if is_numeric(col) else ""
		header_cells += "<th" + css + ">" + escape_html(str(_(col.get("label") or col["fieldname"]))) + "</th>"
	headers_html = "<tr>" + header_cells + "</tr>"

	def render_cell(col, row):
		value = row.get(col["fieldname"])
		if value is None or value == "":
			return ""
		fieldtype = col.get("fieldtype")
		if fieldtype == "Currency":
			return fmt_money(flt(value), currency=row.get("currency") or currency)
		if fieldtype == "Float":
			return f"{flt(value):,.2f}"
		if fieldtype == "Int":
			return str(cint(value))
		if fieldtype == "Date":
			return formatdate(value)
		return escape_html(str(value))

	rows_html = ""
	for i, row in enumerate(rows):
		css = "odd" if i % 2 == 0 else "even"
		cells = ""
		for col in columns:
			cell_css = ' class="text-right"' if is_numeric(col) else ""
			cells += "<td" + cell_css + ">" + render_cell(col, row) + "</td>"
		rows_html += '<tr class="' + css + '">' + cells + "</tr>"

	totals_cells = ""
	label_done = False
	for col in columns:
		# age is per-voucher; a summed age would be meaningless
		if is_numeric(col) and col["fieldname"] != "age":
			total = sum(flt(r.get(col["fieldname"])) for r in rows)
			if col.get("fieldtype") == "Currency":
				formatted = fmt_money(total, currency=currency)
			else:
				formatted = f"{total:,.2f}"
			totals_cells += '<td class="text-right">' + formatted + "</td>"
		elif not label_done:
			totals_cells += "<td><b>" + _("TOTAL") + "</b></td>"
			label_done = True
		else:
			totals_cells += "<td></td>"
	totals_html = '<tr class="totals-row">' + totals_cells + "</tr>"

	return headers_html, rows_html, totals_html
